version: 2

models:
  - name: stg_yellow_trips
    description: "Vue standardisée des courses de taxis jaunes"
    columns:
      - name: pickup_datetime
        description: "Horodatage de la prise en charge"
        tests:
          - not_null
      
      - name: dropoff_datetime
        description: "Horodatage de la dépose"
        tests:
          - not_null
          
      - name: trip_distance
        description: "Distance de la course en miles"
        tests:
          - not_null

  - name: mart_daily_trips
    description: "Agrégations quotidiennes des courses"
    columns:
      - name: trip_date
        description: "Date de la course"
        tests:
          - not_null
          - unique
      
      - name: total_trips
        description: "Nombre total de courses pour la journée"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a au moins 1 course
      
      - name: active_vendors
        description: "Nombre de vendeurs actifs dans la journée"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a au moins 1 vendeur actif

      - name: total_passengers
        description: "Nombre total de passagers"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a des passagers dans les courses

      - name: avg_distance
        description: "Distance moyenne des courses"
        tests:
          - not_null
          - greater_than: 0  # Assurer que la distance moyenne est positive

      - name: avg_duration_minutes
        description: "Durée moyenne des courses en minutes"
        tests:
          - not_null
          - greater_than: 0  # Assurer que la durée moyenne est positive

      - name: total_fare
        description: "Montant total des courses"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a des montants de courses positifs

      - name: total_tips
        description: "Total des pourboires"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a des pourboires positifs

      - name: total_revenue
        description: "Revenu total des courses"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a des revenus positifs

      - name: avg_tip_percentage
        description: "Pourcentage moyen de pourboire par rapport au tarif"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a un pourcentage moyen valide

      - name: invalid_trips
        description: "Nombre de courses invalides"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a au moins des courses invalides détectées

  - name: mart_zone_analysis
    description: "Analyse des courses par zone géographique"
    columns:
      - name: pickup_location_id
        description: "ID de la zone de prise en charge"
        tests:
          - not_null
          - unique

      - name: trips_starting
        description: "Nombre de courses démarrant dans la zone de prise en charge"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a au moins 1 course qui commence dans cette zone

      - name: avg_fare
        description: "Tarif moyen des courses démarrant dans la zone de prise en charge"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a un tarif moyen positif

      - name: avg_distance
        description: "Distance moyenne des courses démarrant dans la zone de prise en charge"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a une distance moyenne positive

      - name: total_revenue
        description: "Revenu total des courses démarrant dans la zone de prise en charge"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a des revenus positifs

      - name: location_id
        description: "ID de la zone de dépose"
        tests:
          - not_null
          - unique

      - name: trips_ending
        description: "Nombre de courses finissant dans la zone de dépose"
        tests:
          - not_null
          - greater_than: 0  # Assurer qu'il y a au moins 1 course qui termine dans cette zone
